version: '3.0'
services:
  web:
    image: d3catalyst/dkr-magento2:latest
    ports:
      - "9090:80"
    links:
      - db
    volumes: 
      - ./magento_web:/var/www/html  
    env_file:
      - env
  db:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - env

volumes:
  magento_web:
  mysql_data: 